config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  post 'top/logout'
  root 'top#main'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:uid].nil?
            render 'main'
        else
            render 'login'
        end
    end

    def login
        @user = User.all
        @user.length.times do |i|
            if params[:uid] == @user[i].uid and params[:pass] == @user[i].pass
                session[:uid] = params[:uid]
                flash[:notice] = "ログイン成功！"
                redirect_to '/'
            end
        end
        if session[:uid].nil?
            render 'error'
        end
    end

    def logout
        session.delete(:uid)
        redirect_to '/'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>L42</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/error.html.erb
<p>ログイン失敗!</p>
<%= link_to '戻る','/' %>

app/views/top/login.html.erb
<% flash.each do |type, msg| %>
<%= msg %>
<% end %>
<h1><%= "#{session[:uid]}" %>がログイン中です</h1>
<p><%= link_to 'ログアウト', top_logout_path, method: :post %></p>

app/views/top/main.html.erb
<%= form_tag '/top/login', method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag '登録' %>
 <% end %>